#!/usr/bin/env bash
set -euo pipefail

REDC_PORT="${REDC_PORT:-3000}"
REDC_DB_PATH="${REDC_DB_PATH:-/data/redc-dev.db}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-s3}"
MINIO_PORT="${MINIO_PORT:-9000}"
MINIO_USE_SSL="${MINIO_USE_SSL:-false}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-minioadmin}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-minioadmin}"
MINIO_BUCKET="${MINIO_BUCKET:-redc-artifacts}"
MINIO_PREFIX="${MINIO_PREFIX:-claw-runs}"
MINIO_API_PORT="${MINIO_API_PORT:-9003}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9002}"
WIDE_EVENTS_HOST="${WIDE_EVENTS_HOST:-0.0.0.0}"
WIDE_EVENTS_PORT="${WIDE_EVENTS_PORT:-4090}"
WIDE_EVENTS_STORAGE_BACKEND="${WIDE_EVENTS_STORAGE_BACKEND:-minio}"
WIDE_EVENTS_DATA_DIR="${WIDE_EVENTS_DATA_DIR:-/data/wide-events}"
WIDE_EVENTS_RAW_EVENTS_DIR="${WIDE_EVENTS_RAW_EVENTS_DIR:-/data/wide-events/raw}"
WIDE_EVENTS_ROLLUP_DIR="${WIDE_EVENTS_ROLLUP_DIR:-/data/wide-events/rollup}"
WIDE_EVENTS_S3_ENDPOINT="${WIDE_EVENTS_S3_ENDPOINT:-http://s3:9000}"
WIDE_EVENTS_S3_REGION="${WIDE_EVENTS_S3_REGION:-us-east-1}"
WIDE_EVENTS_S3_ACCESS_KEY_ID="${WIDE_EVENTS_S3_ACCESS_KEY_ID:-$MINIO_ACCESS_KEY}"
WIDE_EVENTS_S3_SECRET_ACCESS_KEY="${WIDE_EVENTS_S3_SECRET_ACCESS_KEY:-$MINIO_SECRET_KEY}"
WIDE_EVENTS_RAW_BUCKET="${WIDE_EVENTS_RAW_BUCKET:-wide-events-raw}"
WIDE_EVENTS_RAW_PREFIX="${WIDE_EVENTS_RAW_PREFIX:-raw}"
WIDE_EVENTS_ROLLUP_BUCKET="${WIDE_EVENTS_ROLLUP_BUCKET:-wide-events-rollup}"
WIDE_EVENTS_ROLLUP_PREFIX="${WIDE_EVENTS_ROLLUP_PREFIX:-rollup}"
WIDE_EVENTS_SWEEP_INTERVAL_MS="${WIDE_EVENTS_SWEEP_INTERVAL_MS:-5000}"
WIDE_EVENTS_INCOMPLETE_GRACE_MS="${WIDE_EVENTS_INCOMPLETE_GRACE_MS:-60000}"
WIDE_EVENTS_REPLAY_WINDOW_MS="${WIDE_EVENTS_REPLAY_WINDOW_MS:-600000}"
OBS_SINK_MODE="${OBS_SINK_MODE:-collector}"
WIDE_EVENTS_COLLECTOR_URL="${WIDE_EVENTS_COLLECTOR_URL:-http://obs:4090}"
GIT_STORAGE_PUBLIC_URL="${GIT_STORAGE_PUBLIC_URL:-http://grs:8080}"
GIT_STORAGE_DEFAULT_OWNER="${GIT_STORAGE_DEFAULT_OWNER:-redc}"
COMPOSE_FILE="${COMPOSE_FILE:-infra/compose/dev.yml}"
SKIP_IMAGE_BUILD="${SKIP_IMAGE_BUILD:-false}"

mkdir -p apps/auth/compose
if [[ ! -f apps/auth/compose/signing-key.private.jwk ]]; then
  echo "Generating auth signing key..."
  (
    cd apps/auth && \
      bun --eval 'import { writeFileSync } from "node:fs"; import { generateKeyPairSync } from "node:crypto"; import { exportJWK } from "jose"; const { privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 }); const jwk = await exportJWK(privateKey); writeFileSync("compose/signing-key.private.jwk", `${JSON.stringify(jwk, null, 2)}\n`);'
  )
fi

echo "Writing .env..."
cat > .env <<EOF
GIT_STORAGE_PUBLIC_URL=$GIT_STORAGE_PUBLIC_URL
GIT_STORAGE_DEFAULT_OWNER=$GIT_STORAGE_DEFAULT_OWNER
REDC_PORT=$REDC_PORT
REDC_DB_PATH=$REDC_DB_PATH
OPENCODE_RUNNER_IMAGE=redc-claw-runner
MINIO_ENDPOINT=$MINIO_ENDPOINT
MINIO_PORT=$MINIO_PORT
MINIO_USE_SSL=$MINIO_USE_SSL
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY
MINIO_BUCKET=$MINIO_BUCKET
MINIO_PREFIX=$MINIO_PREFIX
MINIO_API_PORT=$MINIO_API_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
WIDE_EVENTS_HOST=$WIDE_EVENTS_HOST
WIDE_EVENTS_PORT=$WIDE_EVENTS_PORT
WIDE_EVENTS_STORAGE_BACKEND=$WIDE_EVENTS_STORAGE_BACKEND
WIDE_EVENTS_DATA_DIR=$WIDE_EVENTS_DATA_DIR
WIDE_EVENTS_RAW_EVENTS_DIR=$WIDE_EVENTS_RAW_EVENTS_DIR
WIDE_EVENTS_ROLLUP_DIR=$WIDE_EVENTS_ROLLUP_DIR
WIDE_EVENTS_S3_ENDPOINT=$WIDE_EVENTS_S3_ENDPOINT
WIDE_EVENTS_S3_REGION=$WIDE_EVENTS_S3_REGION
WIDE_EVENTS_S3_ACCESS_KEY_ID=$WIDE_EVENTS_S3_ACCESS_KEY_ID
WIDE_EVENTS_S3_SECRET_ACCESS_KEY=$WIDE_EVENTS_S3_SECRET_ACCESS_KEY
WIDE_EVENTS_RAW_BUCKET=$WIDE_EVENTS_RAW_BUCKET
WIDE_EVENTS_RAW_PREFIX=$WIDE_EVENTS_RAW_PREFIX
WIDE_EVENTS_ROLLUP_BUCKET=$WIDE_EVENTS_ROLLUP_BUCKET
WIDE_EVENTS_ROLLUP_PREFIX=$WIDE_EVENTS_ROLLUP_PREFIX
WIDE_EVENTS_SWEEP_INTERVAL_MS=$WIDE_EVENTS_SWEEP_INTERVAL_MS
WIDE_EVENTS_INCOMPLETE_GRACE_MS=$WIDE_EVENTS_INCOMPLETE_GRACE_MS
WIDE_EVENTS_REPLAY_WINDOW_MS=$WIDE_EVENTS_REPLAY_WINDOW_MS
OBS_SINK_MODE=$OBS_SINK_MODE
WIDE_EVENTS_COLLECTOR_URL=$WIDE_EVENTS_COLLECTOR_URL
EOF

if [[ "$SKIP_IMAGE_BUILD" != "true" ]]; then
  echo "Building Claw runner image..."
  docker build -t redc-claw-runner apps/ocr/

  echo "Building Docker-backed dev services..."
  docker compose --env-file .env -f "$COMPOSE_FILE" build grs ctl
else
  echo "Skipping image builds (SKIP_IMAGE_BUILD=true)"
fi

echo "Starting dev stack..."
docker compose --env-file .env -f "$COMPOSE_FILE" up -d s3 init obs grs db-auth auth ctl bff web

echo ""
echo "=== Setup complete ==="
echo "UI:      http://localhost:5173"
echo "CTL:     http://localhost:3000"
echo "BFF:     http://localhost:3001"
echo "Auth:    http://localhost:4020"
echo "OBS:     http://localhost:$WIDE_EVENTS_PORT"
echo "Git:     http://localhost:9080"
echo "MinIO:   http://localhost:$MINIO_CONSOLE_PORT"
echo "S3 API:  http://localhost:$MINIO_API_PORT"
