#!/usr/bin/env bash
set -euo pipefail

RED_PORT="${RED_PORT:-3000}"
RED_DB_PATH="${RED_DB_PATH:-/data/red-dev.db}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-s3}"
MINIO_PORT="${MINIO_PORT:-9000}"
MINIO_USE_SSL="${MINIO_USE_SSL:-false}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-minioadmin}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-minioadmin}"
MINIO_BUCKET="${MINIO_BUCKET:-red-artifacts}"
MINIO_PREFIX="${MINIO_PREFIX:-claw-runs}"
MINIO_API_PORT="${MINIO_API_PORT:-9003}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9002}"
LOKI_PORT="${LOKI_PORT:-3100}"
LOKI_URL="${LOKI_URL:-http://loki:3100}"
WIDE_EVENTS_HOST="${WIDE_EVENTS_HOST:-0.0.0.0}"
WIDE_EVENTS_PORT="${WIDE_EVENTS_PORT:-4090}"
WIDE_EVENTS_STORAGE_BACKEND="${WIDE_EVENTS_STORAGE_BACKEND:-minio}"
WIDE_EVENTS_DATA_DIR="${WIDE_EVENTS_DATA_DIR:-/data/wide-events}"
WIDE_EVENTS_RAW_EVENTS_DIR="${WIDE_EVENTS_RAW_EVENTS_DIR:-/data/wide-events/raw}"
WIDE_EVENTS_ROLLUP_DIR="${WIDE_EVENTS_ROLLUP_DIR:-/data/wide-events/rollup}"
WIDE_EVENTS_S3_ENDPOINT="${WIDE_EVENTS_S3_ENDPOINT:-http://s3:9000}"
WIDE_EVENTS_S3_REGION="${WIDE_EVENTS_S3_REGION:-us-east-1}"
WIDE_EVENTS_S3_ACCESS_KEY_ID="${WIDE_EVENTS_S3_ACCESS_KEY_ID:-$MINIO_ACCESS_KEY}"
WIDE_EVENTS_S3_SECRET_ACCESS_KEY="${WIDE_EVENTS_S3_SECRET_ACCESS_KEY:-$MINIO_SECRET_KEY}"
WIDE_EVENTS_RAW_BUCKET="${WIDE_EVENTS_RAW_BUCKET:-wide-events-raw}"
WIDE_EVENTS_RAW_PREFIX="${WIDE_EVENTS_RAW_PREFIX:-raw}"
WIDE_EVENTS_ROLLUP_BUCKET="${WIDE_EVENTS_ROLLUP_BUCKET:-wide-events-rollup}"
WIDE_EVENTS_ROLLUP_PREFIX="${WIDE_EVENTS_ROLLUP_PREFIX:-rollup}"
AI_DAEMONS_MEMORY_BACKEND="${AI_DAEMONS_MEMORY_BACKEND:-r2}"
AI_DAEMONS_MEMORY_REPO="${AI_DAEMONS_MEMORY_REPO:-}"
AI_DAEMONS_R2_BUCKET="${AI_DAEMONS_R2_BUCKET:-}"
AI_DAEMONS_R2_ENDPOINT="${AI_DAEMONS_R2_ENDPOINT:-}"
AI_DAEMONS_R2_REGION="${AI_DAEMONS_R2_REGION:-auto}"
AI_DAEMONS_R2_ACCESS_KEY_ID="${AI_DAEMONS_R2_ACCESS_KEY_ID:-}"
AI_DAEMONS_R2_SECRET_ACCESS_KEY="${AI_DAEMONS_R2_SECRET_ACCESS_KEY:-}"
AI_DAEMONS_MEMORY_PREFIX="${AI_DAEMONS_MEMORY_PREFIX:-daemon-memory/v1}"
WIDE_EVENTS_SWEEP_INTERVAL_MS="${WIDE_EVENTS_SWEEP_INTERVAL_MS:-5000}"
WIDE_EVENTS_INCOMPLETE_GRACE_MS="${WIDE_EVENTS_INCOMPLETE_GRACE_MS:-60000}"
WIDE_EVENTS_REPLAY_WINDOW_MS="${WIDE_EVENTS_REPLAY_WINDOW_MS:-600000}"
OBS_SINK_MODE="${OBS_SINK_MODE:-collector}"
WIDE_EVENTS_COLLECTOR_URL="${WIDE_EVENTS_COLLECTOR_URL:-http://obs:4090}"
GIT_STORAGE_PUBLIC_URL="${GIT_STORAGE_PUBLIC_URL:-http://grs:8080}"
GIT_STORAGE_DEFAULT_OWNER="${GIT_STORAGE_DEFAULT_OWNER:-red}"
TRIAGE_ENABLED="${TRIAGE_ENABLED:-false}"
TRIAGE_ENDPOINT_URL="${TRIAGE_ENDPOINT_URL:-http://triage:7000/v1/runs}"
TRIAGE_MIN_STATUS_CODE="${TRIAGE_MIN_STATUS_CODE:-500}"
TRIAGE_DEDUP_TTL_MS="${TRIAGE_DEDUP_TTL_MS:-900000}"
TRIAGE_WORKFLOW_MODE="${TRIAGE_WORKFLOW_MODE:-stub}"
TRIAGE_SMITHERS_BASE_URL="${TRIAGE_SMITHERS_BASE_URL:-http://triage-smithers:7331}"
TRIAGE_WORKFLOW_PATH="${TRIAGE_WORKFLOW_PATH:-/app/apps/triage/src/workflows/triage.tsx}"
TRIAGE_SMITHERS_DB_PATH="${TRIAGE_SMITHERS_DB_PATH:-/smithers-data/smithers.db}"
TRIAGE_AGENT_MODE="${TRIAGE_AGENT_MODE:-subscription}"
TRIAGE_SUBSCRIPTION_MODEL="${TRIAGE_SUBSCRIPTION_MODEL:-gpt-5.3-codex}"
TRIAGE_SUBSCRIPTION_REASONING_EFFORT="${TRIAGE_SUBSCRIPTION_REASONING_EFFORT:-high}"
TRIAGE_OPENAI_BASE_URL="${TRIAGE_OPENAI_BASE_URL:-https://openrouter.ai/api/v1}"
TRIAGE_OPENAI_API_KEY="${TRIAGE_OPENAI_API_KEY:-}"
TRIAGE_OPENAI_MODEL="${TRIAGE_OPENAI_MODEL:-anthropic/claude-sonnet-4.5}"
TRIAGE_OPENAI_PROVIDER_NAME="${TRIAGE_OPENAI_PROVIDER_NAME:-openrouter}"
TRIAGE_OPENAI_TITLE="${TRIAGE_OPENAI_TITLE:-red}"
TRIAGE_OPENAI_REFERER="${TRIAGE_OPENAI_REFERER:-}"
OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"
SMITHERS_API_KEY="${SMITHERS_API_KEY:-}"
SMITHERS_SERVER_PORT="${SMITHERS_SERVER_PORT:-7331}"
AUTH_LAB_STEALTH_TOTP_EMAILS="${AUTH_LAB_STEALTH_TOTP_EMAILS:-douglasjbinder@gmail.com}"
AUTH_LAB_STEALTH_TOTP_SEED_EMAIL="${AUTH_LAB_STEALTH_TOTP_SEED_EMAIL:-douglasjbinder@gmail.com}"
AUTH_LAB_STEALTH_TOTP_SEED_NAME="${AUTH_LAB_STEALTH_TOTP_SEED_NAME:-Douglas Binder}"
AUTH_LAB_STEALTH_TOTP_SEED_SECRET="${AUTH_LAB_STEALTH_TOTP_SEED_SECRET:-JBSWY3DPEHPK3PXP}"
VITE_DEV_AUTO_LOGIN_EMAIL="${VITE_DEV_AUTO_LOGIN_EMAIL:-douglasjbinder@gmail.com}"
VITE_DEV_AUTO_LOGIN_CODE="${VITE_DEV_AUTO_LOGIN_CODE:-000000}"
DEV_REPO_SEED_ENABLED="${DEV_REPO_SEED_ENABLED:-true}"
DEV_REPO_SEED_REMOTE_URL="${DEV_REPO_SEED_REMOTE_URL:-https://github.com/Bind/red.git}"
DEV_REPO_SEED_OWNER="${DEV_REPO_SEED_OWNER:-bind}"
DEV_REPO_SEED_NAME="${DEV_REPO_SEED_NAME:-red}"
DEV_REPO_SEED_BRANCH="${DEV_REPO_SEED_BRANCH:-main}"
COMPOSE_FILE="${COMPOSE_FILE:-infra/dev/compose.yml}"
SKIP_IMAGE_BUILD="${SKIP_IMAGE_BUILD:-false}"
GIT_COMMIT="${GIT_COMMIT:-$(git rev-parse HEAD 2>/dev/null || echo unknown)}"

mkdir -p apps/auth/compose
if [[ ! -f apps/auth/compose/signing-key.private.jwk ]]; then
  echo "Generating auth signing key..."
  (
    cd apps/auth && \
      bun --eval 'import { writeFileSync } from "node:fs"; import { generateKeyPairSync } from "node:crypto"; import { exportJWK } from "jose"; const { privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 }); const jwk = await exportJWK(privateKey); writeFileSync("compose/signing-key.private.jwk", `${JSON.stringify(jwk, null, 2)}\n`);'
  )
fi

echo "Writing .env..."
cat > .env <<EOF
GIT_STORAGE_PUBLIC_URL=$GIT_STORAGE_PUBLIC_URL
GIT_STORAGE_DEFAULT_OWNER=$GIT_STORAGE_DEFAULT_OWNER
RED_PORT=$RED_PORT
RED_DB_PATH=$RED_DB_PATH
OPENCODE_RUNNER_IMAGE=red-claw-runner
MINIO_ENDPOINT=$MINIO_ENDPOINT
MINIO_PORT=$MINIO_PORT
MINIO_USE_SSL=$MINIO_USE_SSL
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY
MINIO_BUCKET=$MINIO_BUCKET
MINIO_PREFIX=$MINIO_PREFIX
MINIO_API_PORT=$MINIO_API_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
LOKI_PORT=$LOKI_PORT
LOKI_URL=$LOKI_URL
WIDE_EVENTS_HOST=$WIDE_EVENTS_HOST
WIDE_EVENTS_PORT=$WIDE_EVENTS_PORT
WIDE_EVENTS_STORAGE_BACKEND=$WIDE_EVENTS_STORAGE_BACKEND
WIDE_EVENTS_DATA_DIR=$WIDE_EVENTS_DATA_DIR
WIDE_EVENTS_RAW_EVENTS_DIR=$WIDE_EVENTS_RAW_EVENTS_DIR
WIDE_EVENTS_ROLLUP_DIR=$WIDE_EVENTS_ROLLUP_DIR
WIDE_EVENTS_S3_ENDPOINT=$WIDE_EVENTS_S3_ENDPOINT
WIDE_EVENTS_S3_REGION=$WIDE_EVENTS_S3_REGION
WIDE_EVENTS_S3_ACCESS_KEY_ID=$WIDE_EVENTS_S3_ACCESS_KEY_ID
WIDE_EVENTS_S3_SECRET_ACCESS_KEY=$WIDE_EVENTS_S3_SECRET_ACCESS_KEY
WIDE_EVENTS_RAW_BUCKET=$WIDE_EVENTS_RAW_BUCKET
WIDE_EVENTS_RAW_PREFIX=$WIDE_EVENTS_RAW_PREFIX
WIDE_EVENTS_ROLLUP_BUCKET=$WIDE_EVENTS_ROLLUP_BUCKET
WIDE_EVENTS_ROLLUP_PREFIX=$WIDE_EVENTS_ROLLUP_PREFIX
AI_DAEMONS_MEMORY_BACKEND=$AI_DAEMONS_MEMORY_BACKEND
AI_DAEMONS_MEMORY_REPO=$AI_DAEMONS_MEMORY_REPO
AI_DAEMONS_R2_BUCKET=$AI_DAEMONS_R2_BUCKET
AI_DAEMONS_R2_ENDPOINT=$AI_DAEMONS_R2_ENDPOINT
AI_DAEMONS_R2_REGION=$AI_DAEMONS_R2_REGION
AI_DAEMONS_R2_ACCESS_KEY_ID=$AI_DAEMONS_R2_ACCESS_KEY_ID
AI_DAEMONS_R2_SECRET_ACCESS_KEY=$AI_DAEMONS_R2_SECRET_ACCESS_KEY
AI_DAEMONS_MEMORY_PREFIX=$AI_DAEMONS_MEMORY_PREFIX
WIDE_EVENTS_SWEEP_INTERVAL_MS=$WIDE_EVENTS_SWEEP_INTERVAL_MS
WIDE_EVENTS_INCOMPLETE_GRACE_MS=$WIDE_EVENTS_INCOMPLETE_GRACE_MS
WIDE_EVENTS_REPLAY_WINDOW_MS=$WIDE_EVENTS_REPLAY_WINDOW_MS
OBS_SINK_MODE=$OBS_SINK_MODE
WIDE_EVENTS_COLLECTOR_URL=$WIDE_EVENTS_COLLECTOR_URL
TRIAGE_ENABLED=$TRIAGE_ENABLED
TRIAGE_ENDPOINT_URL=$TRIAGE_ENDPOINT_URL
TRIAGE_MIN_STATUS_CODE=$TRIAGE_MIN_STATUS_CODE
TRIAGE_DEDUP_TTL_MS=$TRIAGE_DEDUP_TTL_MS
TRIAGE_WORKFLOW_MODE=$TRIAGE_WORKFLOW_MODE
TRIAGE_SMITHERS_BASE_URL=$TRIAGE_SMITHERS_BASE_URL
TRIAGE_WORKFLOW_PATH=$TRIAGE_WORKFLOW_PATH
TRIAGE_SMITHERS_DB_PATH=$TRIAGE_SMITHERS_DB_PATH
TRIAGE_AGENT_MODE=$TRIAGE_AGENT_MODE
TRIAGE_SUBSCRIPTION_MODEL=$TRIAGE_SUBSCRIPTION_MODEL
TRIAGE_SUBSCRIPTION_REASONING_EFFORT=$TRIAGE_SUBSCRIPTION_REASONING_EFFORT
TRIAGE_OPENAI_BASE_URL=$TRIAGE_OPENAI_BASE_URL
TRIAGE_OPENAI_API_KEY=$TRIAGE_OPENAI_API_KEY
TRIAGE_OPENAI_MODEL=$TRIAGE_OPENAI_MODEL
TRIAGE_OPENAI_PROVIDER_NAME=$TRIAGE_OPENAI_PROVIDER_NAME
TRIAGE_OPENAI_TITLE=$TRIAGE_OPENAI_TITLE
TRIAGE_OPENAI_REFERER=$TRIAGE_OPENAI_REFERER
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
SMITHERS_API_KEY=$SMITHERS_API_KEY
SMITHERS_SERVER_PORT=$SMITHERS_SERVER_PORT
AUTH_LAB_STEALTH_TOTP_EMAILS=$AUTH_LAB_STEALTH_TOTP_EMAILS
AUTH_LAB_STEALTH_TOTP_SEED_EMAIL=$AUTH_LAB_STEALTH_TOTP_SEED_EMAIL
AUTH_LAB_STEALTH_TOTP_SEED_NAME="${AUTH_LAB_STEALTH_TOTP_SEED_NAME}"
AUTH_LAB_STEALTH_TOTP_SEED_SECRET=$AUTH_LAB_STEALTH_TOTP_SEED_SECRET
VITE_DEV_AUTO_LOGIN_EMAIL=$VITE_DEV_AUTO_LOGIN_EMAIL
VITE_DEV_AUTO_LOGIN_CODE=$VITE_DEV_AUTO_LOGIN_CODE
GIT_COMMIT=$GIT_COMMIT
EOF

# Append secrets from the dotenvx-encrypted .env.development so local dev can
# exercise anything that needs an API key (triage, etc.). Silently no-ops if
# dotenvx isn't installed or the file isn't present yet.
if [[ -f .env.development ]] && command -v dotenvx >/dev/null 2>&1; then
  echo "Appending decrypted .env.development..."
  dotenvx decrypt -f .env.development --stdout >> .env
fi

echo "Syncing container Bun dependencies..."
docker compose --env-file .env -f "$COMPOSE_FILE" run --rm --no-deps ctl bun install --frozen-lockfile
docker compose --env-file .env -f "$COMPOSE_FILE" run --rm --no-deps auth bun install --frozen-lockfile

if [[ "$SKIP_IMAGE_BUILD" != "true" ]]; then
  echo "Building Claw runner image..."
  docker build -t red-claw-runner apps/ocr/

  echo "Building shared workspace dependency images..."
  docker build \
    -f infra/base/Dockerfile.workspace-deps \
    --build-arg BUN_IMAGE=oven/bun:1-alpine \
    -t red-workspace-deps-alpine:dev \
    .

  echo "Building Docker-backed dev services..."
  docker compose --env-file .env -f "$COMPOSE_FILE" build grs ctl
else
  echo "Skipping image builds (SKIP_IMAGE_BUILD=true)"
fi

echo "Starting dev stack..."
docker compose --env-file .env -f "$COMPOSE_FILE" up -d s3 init obs grs db-auth auth ctl bff web

wait_for_health() {
  local url="$1"
  local label="$2"
  until curl -fsS "$url" >/dev/null 2>&1; do
    echo "Waiting for ${label}..."
    sleep 1
  done
}

seed_dev_repo() {
  if [[ "$DEV_REPO_SEED_ENABLED" != "true" ]]; then
    return
  fi

  local repo_id="${DEV_REPO_SEED_OWNER}/${DEV_REPO_SEED_NAME}"
  local temp_ref="refs/dev-bootstrap/${DEV_REPO_SEED_OWNER}-${DEV_REPO_SEED_NAME}-${DEV_REPO_SEED_BRANCH}"
  local remote_url="http://${GIT_SERVER_ADMIN_USERNAME:-admin}:${GIT_SERVER_ADMIN_PASSWORD:-admin}@127.0.0.1:${GIT_SERVER_PUBLIC_PORT:-9080}/${DEV_REPO_SEED_OWNER}/${DEV_REPO_SEED_NAME}.git"

  curl -fsS -X POST "http://127.0.0.1:3000/api/repos" \
    -H "content-type: application/json" \
    --data "{\"owner\":\"${DEV_REPO_SEED_OWNER}\",\"name\":\"${DEV_REPO_SEED_NAME}\",\"default_branch\":\"${DEV_REPO_SEED_BRANCH}\",\"visibility\":\"private\"}" \
    >/dev/null 2>&1 || true

  echo "Seeding ${repo_id} from ${DEV_REPO_SEED_REMOTE_URL}#${DEV_REPO_SEED_BRANCH}..."
  git fetch --quiet --force "$DEV_REPO_SEED_REMOTE_URL" "refs/heads/${DEV_REPO_SEED_BRANCH}:${temp_ref}"
  git push --quiet --force "$remote_url" "${temp_ref}:refs/heads/${DEV_REPO_SEED_BRANCH}"
  local seeded_sha
  seeded_sha="$(git rev-parse "${temp_ref}")"
  git update-ref -d "${temp_ref}" >/dev/null 2>&1 || true
  echo "Seeded ${repo_id}@${DEV_REPO_SEED_BRANCH} -> ${seeded_sha}"
}

wait_for_health "http://127.0.0.1:${AUTH_PORT:-4020}/health" "auth"
wait_for_health "http://127.0.0.1:${GIT_SERVER_PUBLIC_PORT:-9080}/health" "grs"
wait_for_health "http://127.0.0.1:3000/health" "ctl"
seed_dev_repo

echo ""
echo "=== Setup complete ==="
echo "UI:      http://localhost:5173"
echo "CTL:     http://localhost:3000"
echo "BFF:     http://localhost:3001"
echo "Auth:    http://localhost:4020"
echo "OBS:     http://localhost:$WIDE_EVENTS_PORT"
echo "Git:     http://localhost:9080"
echo "MinIO:   http://localhost:$MINIO_CONSOLE_PORT"
echo "S3 API:  http://localhost:$MINIO_API_PORT"
echo "Loki:    http://localhost:$LOKI_PORT"
