#!/usr/bin/env bash
set -euo pipefail

REDC_PORT="${REDC_PORT:-3000}"
REDC_DB_PATH="${REDC_DB_PATH:-/data/redc-dev.db}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-s3}"
MINIO_PORT="${MINIO_PORT:-9000}"
MINIO_USE_SSL="${MINIO_USE_SSL:-false}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-minioadmin}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-minioadmin}"
MINIO_BUCKET="${MINIO_BUCKET:-redc-artifacts}"
MINIO_PREFIX="${MINIO_PREFIX:-claw-runs}"
MINIO_API_PORT="${MINIO_API_PORT:-9003}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9002}"
WIDE_EVENTS_HOST="${WIDE_EVENTS_HOST:-0.0.0.0}"
WIDE_EVENTS_PORT="${WIDE_EVENTS_PORT:-4090}"
WIDE_EVENTS_STORAGE_BACKEND="${WIDE_EVENTS_STORAGE_BACKEND:-minio}"
WIDE_EVENTS_DATA_DIR="${WIDE_EVENTS_DATA_DIR:-/data/wide-events}"
WIDE_EVENTS_RAW_EVENTS_DIR="${WIDE_EVENTS_RAW_EVENTS_DIR:-/data/wide-events/raw}"
WIDE_EVENTS_ROLLUP_DIR="${WIDE_EVENTS_ROLLUP_DIR:-/data/wide-events/rollup}"
WIDE_EVENTS_S3_ENDPOINT="${WIDE_EVENTS_S3_ENDPOINT:-http://s3:9000}"
WIDE_EVENTS_S3_REGION="${WIDE_EVENTS_S3_REGION:-us-east-1}"
WIDE_EVENTS_S3_ACCESS_KEY_ID="${WIDE_EVENTS_S3_ACCESS_KEY_ID:-$MINIO_ACCESS_KEY}"
WIDE_EVENTS_S3_SECRET_ACCESS_KEY="${WIDE_EVENTS_S3_SECRET_ACCESS_KEY:-$MINIO_SECRET_KEY}"
WIDE_EVENTS_RAW_BUCKET="${WIDE_EVENTS_RAW_BUCKET:-wide-events-raw}"
WIDE_EVENTS_RAW_PREFIX="${WIDE_EVENTS_RAW_PREFIX:-raw}"
WIDE_EVENTS_ROLLUP_BUCKET="${WIDE_EVENTS_ROLLUP_BUCKET:-wide-events-rollup}"
WIDE_EVENTS_ROLLUP_PREFIX="${WIDE_EVENTS_ROLLUP_PREFIX:-rollup}"
WIDE_EVENTS_SWEEP_INTERVAL_MS="${WIDE_EVENTS_SWEEP_INTERVAL_MS:-5000}"
WIDE_EVENTS_INCOMPLETE_GRACE_MS="${WIDE_EVENTS_INCOMPLETE_GRACE_MS:-60000}"
WIDE_EVENTS_REPLAY_WINDOW_MS="${WIDE_EVENTS_REPLAY_WINDOW_MS:-600000}"
OBS_SINK_MODE="${OBS_SINK_MODE:-collector}"
WIDE_EVENTS_COLLECTOR_URL="${WIDE_EVENTS_COLLECTOR_URL:-http://obs:4090}"
GIT_STORAGE_PUBLIC_URL="${GIT_STORAGE_PUBLIC_URL:-http://grs:8080}"
GIT_STORAGE_DEFAULT_OWNER="${GIT_STORAGE_DEFAULT_OWNER:-redc}"
TRIAGE_ENABLED="${TRIAGE_ENABLED:-false}"
TRIAGE_ENDPOINT_URL="${TRIAGE_ENDPOINT_URL:-http://triage:7000/v1/runs}"
TRIAGE_MIN_STATUS_CODE="${TRIAGE_MIN_STATUS_CODE:-500}"
TRIAGE_DEDUP_TTL_MS="${TRIAGE_DEDUP_TTL_MS:-900000}"
TRIAGE_WORKFLOW_MODE="${TRIAGE_WORKFLOW_MODE:-stub}"
TRIAGE_SMITHERS_BASE_URL="${TRIAGE_SMITHERS_BASE_URL:-http://triage-smithers:7331}"
TRIAGE_WORKFLOW_PATH="${TRIAGE_WORKFLOW_PATH:-/app/apps/triage/src/workflows/triage.tsx}"
TRIAGE_SMITHERS_DB_PATH="${TRIAGE_SMITHERS_DB_PATH:-/smithers-data/smithers.db}"
TRIAGE_AGENT_MODE="${TRIAGE_AGENT_MODE:-subscription}"
TRIAGE_SUBSCRIPTION_MODEL="${TRIAGE_SUBSCRIPTION_MODEL:-gpt-5.3-codex}"
TRIAGE_SUBSCRIPTION_REASONING_EFFORT="${TRIAGE_SUBSCRIPTION_REASONING_EFFORT:-high}"
TRIAGE_OPENAI_BASE_URL="${TRIAGE_OPENAI_BASE_URL:-https://openrouter.ai/api/v1}"
TRIAGE_OPENAI_API_KEY="${TRIAGE_OPENAI_API_KEY:-}"
TRIAGE_OPENAI_MODEL="${TRIAGE_OPENAI_MODEL:-anthropic/claude-sonnet-4.5}"
TRIAGE_OPENAI_PROVIDER_NAME="${TRIAGE_OPENAI_PROVIDER_NAME:-openrouter}"
TRIAGE_OPENAI_TITLE="${TRIAGE_OPENAI_TITLE:-redc}"
TRIAGE_OPENAI_REFERER="${TRIAGE_OPENAI_REFERER:-}"
SMITHERS_API_KEY="${SMITHERS_API_KEY:-}"
SMITHERS_SERVER_PORT="${SMITHERS_SERVER_PORT:-7331}"
AUTH_LAB_STEALTH_TOTP_EMAILS="${AUTH_LAB_STEALTH_TOTP_EMAILS:-douglasjbinder@gmail.com}"
AUTH_LAB_STEALTH_TOTP_SEED_EMAIL="${AUTH_LAB_STEALTH_TOTP_SEED_EMAIL:-douglasjbinder@gmail.com}"
AUTH_LAB_STEALTH_TOTP_SEED_NAME="${AUTH_LAB_STEALTH_TOTP_SEED_NAME:-Douglas Binder}"
AUTH_LAB_STEALTH_TOTP_SEED_SECRET="${AUTH_LAB_STEALTH_TOTP_SEED_SECRET:-JBSWY3DPEHPK3PXP}"
COMPOSE_FILE="${COMPOSE_FILE:-infra/dev/compose.yml}"
SKIP_IMAGE_BUILD="${SKIP_IMAGE_BUILD:-false}"
GIT_COMMIT="${GIT_COMMIT:-$(git rev-parse HEAD 2>/dev/null || echo unknown)}"

mkdir -p apps/auth/compose
if [[ ! -f apps/auth/compose/signing-key.private.jwk ]]; then
  echo "Generating auth signing key..."
  (
    cd apps/auth && \
      bun --eval 'import { writeFileSync } from "node:fs"; import { generateKeyPairSync } from "node:crypto"; import { exportJWK } from "jose"; const { privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 }); const jwk = await exportJWK(privateKey); writeFileSync("compose/signing-key.private.jwk", `${JSON.stringify(jwk, null, 2)}\n`);'
  )
fi

echo "Writing .env..."
cat > .env <<EOF
GIT_STORAGE_PUBLIC_URL=$GIT_STORAGE_PUBLIC_URL
GIT_STORAGE_DEFAULT_OWNER=$GIT_STORAGE_DEFAULT_OWNER
REDC_PORT=$REDC_PORT
REDC_DB_PATH=$REDC_DB_PATH
OPENCODE_RUNNER_IMAGE=redc-claw-runner
MINIO_ENDPOINT=$MINIO_ENDPOINT
MINIO_PORT=$MINIO_PORT
MINIO_USE_SSL=$MINIO_USE_SSL
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY
MINIO_BUCKET=$MINIO_BUCKET
MINIO_PREFIX=$MINIO_PREFIX
MINIO_API_PORT=$MINIO_API_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
WIDE_EVENTS_HOST=$WIDE_EVENTS_HOST
WIDE_EVENTS_PORT=$WIDE_EVENTS_PORT
WIDE_EVENTS_STORAGE_BACKEND=$WIDE_EVENTS_STORAGE_BACKEND
WIDE_EVENTS_DATA_DIR=$WIDE_EVENTS_DATA_DIR
WIDE_EVENTS_RAW_EVENTS_DIR=$WIDE_EVENTS_RAW_EVENTS_DIR
WIDE_EVENTS_ROLLUP_DIR=$WIDE_EVENTS_ROLLUP_DIR
WIDE_EVENTS_S3_ENDPOINT=$WIDE_EVENTS_S3_ENDPOINT
WIDE_EVENTS_S3_REGION=$WIDE_EVENTS_S3_REGION
WIDE_EVENTS_S3_ACCESS_KEY_ID=$WIDE_EVENTS_S3_ACCESS_KEY_ID
WIDE_EVENTS_S3_SECRET_ACCESS_KEY=$WIDE_EVENTS_S3_SECRET_ACCESS_KEY
WIDE_EVENTS_RAW_BUCKET=$WIDE_EVENTS_RAW_BUCKET
WIDE_EVENTS_RAW_PREFIX=$WIDE_EVENTS_RAW_PREFIX
WIDE_EVENTS_ROLLUP_BUCKET=$WIDE_EVENTS_ROLLUP_BUCKET
WIDE_EVENTS_ROLLUP_PREFIX=$WIDE_EVENTS_ROLLUP_PREFIX
WIDE_EVENTS_SWEEP_INTERVAL_MS=$WIDE_EVENTS_SWEEP_INTERVAL_MS
WIDE_EVENTS_INCOMPLETE_GRACE_MS=$WIDE_EVENTS_INCOMPLETE_GRACE_MS
WIDE_EVENTS_REPLAY_WINDOW_MS=$WIDE_EVENTS_REPLAY_WINDOW_MS
OBS_SINK_MODE=$OBS_SINK_MODE
WIDE_EVENTS_COLLECTOR_URL=$WIDE_EVENTS_COLLECTOR_URL
TRIAGE_ENABLED=$TRIAGE_ENABLED
TRIAGE_ENDPOINT_URL=$TRIAGE_ENDPOINT_URL
TRIAGE_MIN_STATUS_CODE=$TRIAGE_MIN_STATUS_CODE
TRIAGE_DEDUP_TTL_MS=$TRIAGE_DEDUP_TTL_MS
TRIAGE_WORKFLOW_MODE=$TRIAGE_WORKFLOW_MODE
TRIAGE_SMITHERS_BASE_URL=$TRIAGE_SMITHERS_BASE_URL
TRIAGE_WORKFLOW_PATH=$TRIAGE_WORKFLOW_PATH
TRIAGE_SMITHERS_DB_PATH=$TRIAGE_SMITHERS_DB_PATH
TRIAGE_AGENT_MODE=$TRIAGE_AGENT_MODE
TRIAGE_SUBSCRIPTION_MODEL=$TRIAGE_SUBSCRIPTION_MODEL
TRIAGE_SUBSCRIPTION_REASONING_EFFORT=$TRIAGE_SUBSCRIPTION_REASONING_EFFORT
TRIAGE_OPENAI_BASE_URL=$TRIAGE_OPENAI_BASE_URL
TRIAGE_OPENAI_API_KEY=$TRIAGE_OPENAI_API_KEY
TRIAGE_OPENAI_MODEL=$TRIAGE_OPENAI_MODEL
TRIAGE_OPENAI_PROVIDER_NAME=$TRIAGE_OPENAI_PROVIDER_NAME
TRIAGE_OPENAI_TITLE=$TRIAGE_OPENAI_TITLE
TRIAGE_OPENAI_REFERER=$TRIAGE_OPENAI_REFERER
SMITHERS_API_KEY=$SMITHERS_API_KEY
SMITHERS_SERVER_PORT=$SMITHERS_SERVER_PORT
AUTH_LAB_STEALTH_TOTP_EMAILS=$AUTH_LAB_STEALTH_TOTP_EMAILS
AUTH_LAB_STEALTH_TOTP_SEED_EMAIL=$AUTH_LAB_STEALTH_TOTP_SEED_EMAIL
AUTH_LAB_STEALTH_TOTP_SEED_NAME="${AUTH_LAB_STEALTH_TOTP_SEED_NAME}"
AUTH_LAB_STEALTH_TOTP_SEED_SECRET=$AUTH_LAB_STEALTH_TOTP_SEED_SECRET
GIT_COMMIT=$GIT_COMMIT
EOF

# Append secrets from the dotenvx-encrypted .env.development so local dev can
# exercise anything that needs an API key (triage, etc.). Silently no-ops if
# dotenvx isn't installed or the file isn't present yet.
if [[ -f .env.development ]] && command -v dotenvx >/dev/null 2>&1; then
  echo "Appending decrypted .env.development..."
  dotenvx decrypt -f .env.development --stdout >> .env
fi

if [[ "$SKIP_IMAGE_BUILD" != "true" ]]; then
  echo "Building Claw runner image..."
  docker build -t redc-claw-runner apps/ocr/

  echo "Building shared workspace dependency images..."
  docker build \
    -f infra/base/Dockerfile.workspace-deps \
    --build-arg BUN_IMAGE=oven/bun:1-alpine \
    -t red-workspace-deps-alpine:dev \
    .
  docker build \
    -f infra/base/Dockerfile.workspace-deps \
    --build-arg BUN_IMAGE=oven/bun:1.3.10 \
    -t red-workspace-deps-debian:dev \
    .

  echo "Building Docker-backed dev services..."
  docker compose --env-file .env -f "$COMPOSE_FILE" build grs ctl
else
  echo "Skipping image builds (SKIP_IMAGE_BUILD=true)"
fi

echo "Starting dev stack..."
docker compose --env-file .env -f "$COMPOSE_FILE" up -d s3 init obs grs db-auth auth ctl bff web

echo ""
echo "=== Setup complete ==="
echo "UI:      http://localhost:5173"
echo "CTL:     http://localhost:3000"
echo "BFF:     http://localhost:3001"
echo "Auth:    http://localhost:4020"
echo "OBS:     http://localhost:$WIDE_EVENTS_PORT"
echo "Git:     http://localhost:9080"
echo "MinIO:   http://localhost:$MINIO_CONSOLE_PORT"
echo "S3 API:  http://localhost:$MINIO_API_PORT"
